// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace WorkshopDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.Components;
    using uFrame.Json;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(2)]
    [uFrame.Attributes.uFrameIdentifier("9ee80b2e-58a3-498b-864b-e52af3ff7f94")]
    public partial class Shield : uFrame.ECS.Components.EcsComponent {
        
        public override int ComponentId {
            get {
                return 2;
            }
        }
    }
}
