// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace WorkshopDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.Components;
    using uFrame.Json;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(3)]
    [uFrame.Attributes.uFrameIdentifier("903a2cd8-a5ea-4b88-b2dc-ce130e25ed69")]
    public partial class Sword : uFrame.ECS.Components.EcsComponent {
        
        public override int ComponentId {
            get {
                return 3;
            }
        }
    }
}
