// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace WorkshopDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS.APIs;
    using uFrame.ECS.Components;
    using uFrame.ECS.Systems;
    using uFrame.Kernel;
    using UniRx;
    using UnityEngine;
    
    
    public partial class DebugSystemBase : uFrame.ECS.Systems.EcsSystem {
        
        private IEcsComponentManagerOf<Health> _HealthManager;
        
        private IEcsComponentManagerOf<Sword> _SwordManager;
        
        private IEcsComponentManagerOf<Shield> _ShieldManager;
        
        private IEcsComponentManagerOf<Orc> _OrcManager;
        
        private DebugSystemGameReadyHandler DebugSystemGameReadyHandlerInstance = new DebugSystemGameReadyHandler();
        
        public IEcsComponentManagerOf<Health> HealthManager {
            get {
                return _HealthManager;
            }
            set {
                _HealthManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Sword> SwordManager {
            get {
                return _SwordManager;
            }
            set {
                _SwordManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Shield> ShieldManager {
            get {
                return _ShieldManager;
            }
            set {
                _ShieldManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Orc> OrcManager {
            get {
                return _OrcManager;
            }
            set {
                _OrcManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            HealthManager = ComponentSystem.RegisterComponent<Health>(1);
            SwordManager = ComponentSystem.RegisterComponent<Sword>(3);
            ShieldManager = ComponentSystem.RegisterComponent<Shield>(2);
            OrcManager = ComponentSystem.RegisterGroup<OrcGroup,Orc>();
            this.OnEvent<uFrame.Kernel.GameReadyEvent>().Subscribe(_=>{ DebugSystemGameReadyFilter(_); }).DisposeWith(this);
        }
        
        protected virtual void DebugSystemGameReadyHandler(uFrame.Kernel.GameReadyEvent data) {
            var handler = DebugSystemGameReadyHandlerInstance;
            handler.System = this;
            handler.Event = data;
            StartCoroutine(handler.Execute());
        }
        
        protected void DebugSystemGameReadyFilter(uFrame.Kernel.GameReadyEvent data) {
            this.DebugSystemGameReadyHandler(data);
        }
    }
    
    [uFrame.Attributes.uFrameIdentifier("05562296-0c1a-4332-b33d-46a57bd0f5ef")]
    public partial class DebugSystem : DebugSystemBase {
        
        private static DebugSystem _Instance;
        
        public DebugSystem() {
            Instance = this;
        }
        
        public static DebugSystem Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
    }
}
